[colors.bright]
black = "#737171"
blue = "#009ddc"
cyan = "#85cebc"
green = "#00853e"
magenta = "#98005d"
red = "#ee2e24"
white = "#ffffff"
yellow = "#ffd204"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#231f20"
blue = "#009ddc"
cyan = "#85cebc"
green = "#00853e"
magenta = "#98005d"
red = "#ee2e24"
white = "#d9d8d8"
yellow = "#ffd204"

[colors.primary]
background = "#2a2838"
foreground = "#efefef"

[colors.selection]
background = "#d07300"
text = "CellForeground"

[window]
opacity = 0.85

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Jetbrains Mono"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Control|Shift"

[scrolling]
history = 50000
